### ISSUE TITLE
No text displayed

### ISSUE THREAD

**Issue by kstubb** [VedantParanjape/KiBuzzard#1]
Hi Vedant;

Thanks again for your work. I hope it's just something dumb I'm doing... I'll try to give you as much info as possible.

This is on Ubuntu 20.04. 5.4.0-62-generic #70-Ubuntu

KiCAD Version Info:

> Application: Pcbnew
Version: 5.1.9-73d0e3b20d~88~ubuntu20.04.1, release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Platform: Linux 5.4.0-62-generic x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
    Boost: 1.71.0
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.68.0
    Compiler: GCC 9.3.0 with C++ ABI 1013

> Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=ON
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=ON
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON

It installs fine. Seemingly, but I am a total noob with KiCAD and plugins. I'm wondering if I have it installed correctly, even though it works. I installed the SnapEDA, it wouldn't work inside the folder it came in (within ~/.kicad_plugins/), I had to copy the .py file from it's folder to my ~/.kicad_plugins/ directory for it to work. KiBuzzard is cloned to that directory and loads just like that, so I assume that's all I needed to do. I did look and I didn't see a KiBuzzard.py file to move anyway.

I followed instructions and ran the dependencies.

>kyle@kyle-desktop:~/.kicad_plugins/KiBuzzard$ pip3 install -r requirements.txt --user
Requirement already satisfied: bezier==2020.5.19 in /home/users/kyle/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2020.5.19)
Requirement already satisfied: freetype-py==2.1.0.post1 in /home/users/kyle/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2.1.0.post1)
Requirement already satisfied: numpy==1.18.3 in /home/users/kyle/.local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (1.18.3)
Requirement already satisfied: svgelements==1.0.2 in /home/users/kyle/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (1.0.2)
Requirement already satisfied: svgpathtools==1.3.3 in /home/users/kyle/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (1.3.3)
Requirement already satisfied: svgwrite==1.4 in /home/users/kyle/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.4)

The label creation box pops up, I enter text, hit enter and I get no text displayed (was at board center, but now 0,0). I assume that is what is being said here;

> Since, KiCad stable version doesn't support system clipboard operations, the footprint is placed at (0, 0). Please navigate there and move the label to where you want to place it

Let me know what other information I can provide, or how else I can help.

Regards;
Kyle

**Comment by VedantParanjape** [comment]
Hi, can you do the following,

type `kicad` in terminal and then try to run the plugin through this instance, So now any logs/errors due to the plugin will be printed into the terminal. Please copy the debug text.

Additionally can you run this command in KiBuzzard directory and post the output here, `ls deps/buzzard`

**Comment by kstubb** [comment]
Sure can!

> Traceback (most recent call last):
  File "/home/users/kyle/.kicad_plugins/KiBuzzard/KiBuzzard/dialog/dialog.py", line 21, in OnTextEnter
    self.func(self.m_textCtrl4.GetValue())
  File "/home/users/kyle/.kicad_plugins/KiBuzzard/KiBuzzard/__init__.py", line 146, in run_buzzard
    footprint.SetPosition(pcbnew.wxPointMM(board_center_x, board_center_y))
AttributeError: 'NoneType' object has no attribute 'SetPosition'

ls deps/buzzard

> buzzard.py  makeLabel.ulp  modules  README.md  requirements.txt  tests  typeface

**Comment by VedantParanjape** [comment]
> Sure can!
> 
> > Traceback (most recent call last):
>   File "/home/users/kyle/.kicad_plugins/KiBuzzard/KiBuzzard/dialog/dialog.py", line 21, in OnTextEnter
>     self.func(self.m_textCtrl4.GetValue())
>   File "/home/users/kyle/.kicad_plugins/KiBuzzard/KiBuzzard/__init__.py", line 146, in run_buzzard
>     footprint.SetPosition(pcbnew.wxPointMM(board_center_x, board_center_y))
> AttributeError: 'NoneType' object has no attribute 'SetPosition'
> 
> ls deps/buzzard
> 
> > buzzard.py  makeLabel.ulp  modules  README.md  requirements.txt  tests  typeface
> 
> 

Ah, I see. are you doing this on a saved project? If not, save a project first of all and then try this.

additionally check for the project directory there should be a folder called buzzard_labels.pretty and inside it should be buzzard_labels.kicad_mod.

let me know if it is there.

Edit: You Haven't updated the repo it seems, go into the folder and run git pull.

**Comment by kstubb** [comment]
Yes, it is on a saved project. I'll try it on another to test.

> kyle@kyle-desktop:/home/users/kyle/KiCAD/projects/KAS_ERTFTM050-3_Host_Board$ ls -la
total 3288
drwxrwsr-x 3 kyle kyle    4096 Jan 17 14:20 .
drwxrwxr-x 7 kyle kyle    4096 Jan 16 10:35 ..
drwxrwsr-x 2 kyle kyle    4096 Jan 17 11:47 buzzard_labels.pretty
-rw------- 1 kyle kyle 3004694 Jan 17 14:18 fp-info-cache
-rw-rw-r-- 1 kyle kyle   15644 Jan 17 13:35 KAS_ERTFTM050-3_Host_Board-cache.lib
-rw-rw-r-- 1 kyle kyle  111811 Jan 17 14:20 KAS_ERTFTM050-3_Host_Board.kicad_pcb
-rw-rw-r-- 1 kyle kyle  111787 Jan 17 14:09 KAS_ERTFTM050-3_Host_Board.kicad_pcb-bak
-rw-rw-r-- 1 kyle kyle   38265 Jan 17 14:18 KAS_ERTFTM050-3_Host_Board.net
-rw-r--r-- 1 kyle kyle    3895 Jan 16 21:20 KAS_ERTFTM050-3_Host_Board.pro
-rw-rw-r-- 1 kyle kyle   25400 Jan 17 13:35 KAS_ERTFTM050-3_Host_Board.sch
-rw-rw-r-- 1 kyle kyle   25439 Jan 17 13:14 KAS_ERTFTM050-3_Host_Board.sch-bak
kyle@kyle-desktop:/home/users/kyle/KiCAD/projects/KAS_ERTFTM050-3_Host_Board$ cd buzzard_labels.pretty/
kyle@kyle-desktop:/home/users/kyle/KiCAD/projects/KAS_ERTFTM050-3_Host_Board/buzzard_labels.pretty$ ls -la
total 8
drwxrwsr-x 2 kyle kyle 4096 Jan 17 11:47 .
drwxrwsr-x 3 kyle kyle 4096 Jan 17 14:20 ..
-rw-rw-r-- 1 kyle kyle    0 Jan 17 14:14 buzzard_labels.kicad_mod

Sorry, I did a git fetch. Just did a pull.

> Updating 55e7fbf..0fd6c63
Fast-forward
 KiBuzzard/__init__.py | 9 +++++----
 README.md             | 2 +-
 2 files changed, 6 insertions(+), 5 deletions(-)

Same results, even on a second project.

> {'current_version_release': '0.0.4.6'}
Traceback (most recent call last):
  File "/home/users/kyle/.kicad_plugins/KiBuzzard/KiBuzzard/dialog/dialog.py", line 21, in OnTextEnter
    self.func(self.m_textCtrl4.GetValue())
  File "/home/users/kyle/.kicad_plugins/KiBuzzard/KiBuzzard/__init__.py", line 148, in run_buzzard
    footprint.SetPosition(pcbnew.wxPoint(0, 0))
AttributeError: 'NoneType' object has no attribute 'SetPosition'

**Comment by VedantParanjape** [comment]
@kstubb I am not able to figure it out, tried it fresh on my system and it works. Let's do one thing. Close all instances of kicad (make sure the process is killed).

Delete the KiBuzzard folder from .kicad_plugins and then `git clone https://github.com/VedantParanjape/KiBuzzard.git --recursive` into `.kicad_plugins`.

Fingers crossed it should work this time, and do this by running kicad on terminal, so you can post the logs again if it fails.

Edit: lol xD, you are entering wrong buzzard commands, that's why it is throwing a error 😆 

try with this, i.e enter this in the dialog box : `"<it works>"`

**Comment by kstubb** [comment]
Hi Vedant;

I removed the plugin and did a fresh git clone, restarted, entered "\<it works\>" (both with and without the quotes) and get the same error. I initially tried all kinds of variants of the cmd, such as (test), /test/, \test\, [test], >test> and went to straight text as I don't see anywhere that says encapsulate text in <> (unless you want tails), it should work with no optional arguments, right?

> usage: buzzard.py [-h] [-f FONTNAME] [-s SCALEFACTOR] [-l EAGLELAYERNUMBER]
                  [-v] [-o {b,ls,lib}] [-n SIGNALNAME] [-u SUBSAMPLING]
                  [-t TRACEWIDTH] [-a {tl,cl,bl,tc,cc,bc,tr,cr,br}]
                  labelText

> By default, Buzzard.py will output plain text labels. If you want to make a flag label, you can surround your text with the following special characters: ()[]/\><

Thanks for trying.

Regards;
Kyle

**Comment by VedantParanjape** [comment]
> Hi Vedant;
> 
> I removed the plugin and did a fresh git clone, restarted, entered "\<it works\>" (both with and without the quotes) and get the same error. I initially tried all kinds of variants of the cmd, such as (test), /test/, \test\, [test], >test> and went to straight text as I don't see anywhere that says encapsulate text in <> (unless you want tails), it should work with no optional arguments, right?
> 
> > usage: buzzard.py [-h] [-f FONTNAME] [-s SCALEFACTOR] [-l EAGLELAYERNUMBER]
>                   [-v] [-o {b,ls,lib}] [-n SIGNALNAME] [-u SUBSAMPLING]
>                   [-t TRACEWIDTH] [-a {tl,cl,bl,tc,cc,bc,tr,cr,br}]
>                   labelText
> 
> > By default, Buzzard.py will output plain text labels. If you want to make a flag label, you can surround your text with the following special characters: ()[]/\><
> 
> Thanks for trying.
> 
> Regards;
> Kyle

You need to encapsulate the text in double quotes (" "). I got the same error when I passed buzzard some wrong argument.

I am pulling my hair out, as to why this isn't working. Let me know if you want to share screen and work it.

```
Hey, talk to me on Element: https://matrix.to/#/@vedant16:matrix.org
```

**Comment by kstubb** [comment]
I got it to work this morning. I had set a python alias in my .bash_aliases (alias python=python3), which showed python 3.8 in the terminal, but I didn't know if it was being picked up by KiCAD as 3.8 or 2.7. I installed the package python-is-python3 this morning and "\<it works\>".

[https://twitter.com/KyleStubbins/status/1351164888689872900](https://twitter.com/KyleStubbins/status/1351164888689872900)

Sorry for making you pull your hair out, and thanks for trying to fix my problem.

Regards;
Kyle

**Comment by VedantParanjape** [comment]
> I got it to work this morning. I had set a python alias in my .bash_aliases (alias python=python3), which showed python 3.8 in the terminal, but I didn't know if it was being picked up by KiCAD as 3.8 or 2.7. I installed the package python-is-python3 this morning and "\<it works\>".
> 
> [https://twitter.com/KyleStubbins/status/1351164888689872900](https://twitter.com/KyleStubbins/status/1351164888689872900)
> 
> Sorry for making you pull your hair out, and thanks for trying to fix my problem.
> 
> Regards;
> Kyle
> 
> 

Cool, glad I could help. 

https://twitter.com/vedantparanjap3/status/1351047750675275777?s=19

I have posted about this on my twitter. Feel free to close this issue.

**Comment by tmanaud** [comment]
> I installed the package python-is-python3 this morning and "<it works>".  

Installing the package python-is-python3 fixed this issue for me (no text and no error in console) on :
Pcbnew Version: 5.99.0-unknown-50e22de3ba~107~ubuntu20.04.1, release build Platform: Linux 5.4.0-58-generic x86_64, 64 bit, Little endian, wxGTK, gnome-classic, x11
