### ISSUE TITLE
UI change

### ISSUE THREAD

**Issue by iharshadec** [VedantParanjape/KiBuzzard#5]
https://github.com/gregdavill/KiBuzzard/pull/8
Arturo has made a UI + Command Line when we click on plugin. Is there easy way to change files on his version so we can get his UI working with 5.1.9?

**Comment by VedantParanjape** [comment]
@iharshadec Yes this can be done. I'll try to merge it my freetime. A bit busy these days.

**Comment by dcelectr** [comment]
@VedantParanjape
The version https://github.com/VedantParanjape/KiBuzzard/tree/wip-gui-change worked on Linux, but not on Win10.
A few hours ago I was able to make it work on Win10 my cherry-picked version and I will look into why your version to see why it did not work on Win10.

![CMD](https://user-images.githubusercontent.com/48794887/106646166-5f494a00-655b-11eb-9859-343dfecaa8e8.png)

@iharshadec 
Would you please try the changes from my fork to indecently verify that it works on Win10?

**Comment by VedantParanjape** [comment]
@iharshadec Please check the latest version, I have incorporated changes by @DCelectronics

**Comment by iharshadec** [comment]
> @iharshadec Please check the latest version, I have incorporated changes by @DCelectronics

Right now I have @DCelectronics copy working. Today I will replace it with this master branch and update you if this works directly or not. BTW @gregdavill is also working on something that works with KiCad in-built 2.7 as well.

**Comment by VedantParanjape** [comment]
I will close this issue now
