### ISSUE TITLE
Plugin icon is not visible

### ISSUE THREAD

**Issue by iharshadec** [VedantParanjape/KiBuzzard#7]
@DCelectronics 
You got Requirement.txt getting installed using which python verison on windows?

I am not able to requirement.txt fulfilled.
Python 3.9.1
Windows 10

> pip3 install -r C:\Users\Ecloud12\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\requirements.txt --user
Collecting bezier==2020.5.19
  Using cached bezier-2020.5.19.tar.gz (313 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ecloud12\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ecloud12\\AppData\\Local\\Temp\\pip-install-qej7lz22\\bezier_38a8494f4d2546afb71ea3083aca8ecb\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ecloud12\\AppData\\Local\\Temp\\pip-install-qej7lz22\\bezier_38a8494f4d2546afb71ea3083aca8ecb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Ecloud12\AppData\Local\Temp\pip-pip-egg-info-pvzpdpcx'
         cwd: C:\Users\Ecloud12\AppData\Local\Temp\pip-install-qej7lz22\bezier_38a8494f4d2546afb71ea3083aca8ecb\
    Complete output (1 lines):
    The BEZIER_INSTALL_PREFIX environment variable must be set.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b9/0c/b1982f93c36fc06850a3880bb693bf24a047946633ca7403664836b9da9e/bezier-2020.5.19.tar.gz#sha256=ff75337e5bb4385376aeaa48fc941bcd61b528df43a1e938bfb07fe7d924b19c (from https://pypi.org/simple/bezier/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement bezier==2020.5.19
ERROR: No matching distribution found for bezier==2020.5.19

**Comment by dcelectr** [comment]
@iharshadec 
I got the requirements installed in Windows with Python3.8.? 
The most important step that enabled me to successfully install the requirements (on both Windows and Linux) was to **upgrade the pip first** by running:
```python3 -m pip install --upgrade pip```

Also, look how I ran the requirements installation on Windows below.

![pip3_install](https://user-images.githubusercontent.com/48794887/105621989-47dfc380-5ddb-11eb-82e1-837eb3126100.png)

Last thing, I added the path (shown in the warning above) in my Environment Variables for the user only.

**Comment by iharshadec** [comment]
I got Bezier installed with Greg's tip on how to set variable. Now I have installed all requirement successfully.

Also I setup Path
![image](https://user-images.githubusercontent.com/20681096/106700044-0a184180-660a-11eb-8ea1-f7d230ce405d.png)

And I downloaded @DCelectronics code and pasted in 

> C:\Users\Ecloud12\AppData\Roaming\kicad\scripting\plugins\

But I do not see KiBuzzard Icon on pcbnew.
![image](https://user-images.githubusercontent.com/20681096/106700161-4ba8ec80-660a-11eb-987d-b3eb2ddb1b66.png)

I did Refresh Plugins and Restarted KiCad as well. On @DCelectronics there is no option to generate issue/ticket so I did here itself.

**Comment by dcelectr** [comment]
@iharshadec Which branch did you download?

**Comment by iharshadec** [comment]
> @iharshadec Which branch did you download?

I downloaded your main branch.

**Comment by dcelectr** [comment]
I assume you have installed the prerequisites recursively.
I do not see a TMP or TEMP in your environment variables.

**Comment by iharshadec** [comment]
> I assume you have installed the prerequisites recursively.
> I do not see a TMP or TEMP in your environment variables.

I am not sure then I am missing something major. I was going thru other issues in detail but if you can reference me I can look over that.
Is downloading and using your main branch is OK?

**Comment by dcelectr** [comment]
Yes my main branch is up to date.
Can  you revert the changes in your downloaded files from this update https://github.com/VedantParanjape/KiBuzzard/pull/8/commits/98da54eb867b201f7e59ceffea0a840882a5cf5d

change line 118 to 
``` filepath = os.environ['KIPRJMOD'] + "/" + self.buzzard_label_library_path```

**Comment by iharshadec** [comment]
Ok, Changed line 118
![image](https://user-images.githubusercontent.com/20681096/106702578-93ca0e00-660e-11eb-886a-8116b7c251dc.png)
Still I do not see KiBuzzard Icon on my Plugin list.

@DCelectronics line 118 change is to not have that TMP or TEMP as PATH?

**Comment by dcelectr** [comment]
It was a finicky and you need to restart KiCad (not only PcbNew)
Yes the ```tempfile.gettempdir()``` in line 118 an the ```import tempfile``` in line 6 are used save to system TMP location.

**Comment by iharshadec** [comment]
> It was a finicky and you need to restart KiCad (not only PcbNew)
> Yes the `tempfile.gettempdir()` in line 118 an the `import tempfile` in line 6 are used save to system TMP location.

Restarted KiCad -- Still no KiBuzzard Icon. 
[KiBuzzard.zip](https://github.com/VedantParanjape/KiBuzzard/files/5916314/KiBuzzard.zip)
![image](https://user-images.githubusercontent.com/20681096/106703404-2ae39580-6610-11eb-8c0b-b9c34b5f5b84.png)


Let me restart my machine as well.

**Comment by dcelectr** [comment]
I don't think is necessary to restart the machine.
Would you please try this in your command window? (your path would be different than the one shown below).
![Temp_File_Location](https://user-images.githubusercontent.com/48794887/106703718-d2cd7480-65b8-11eb-9be6-ce99078a7c3f.png)

**Comment by iharshadec** [comment]
> I don't think is necessary to restart the machine.
> Would you please try this in your command window? (your path would be different than the one shown below).
> ![Temp_File_Location](https://user-images.githubusercontent.com/48794887/106703718-d2cd7480-65b8-11eb-9be6-ce99078a7c3f.png)

Here it is.
![image](https://user-images.githubusercontent.com/20681096/106704201-b4e02e00-6611-11eb-9a5d-131b8a70020a.png)

**Comment by dcelectr** [comment]
I am comparing my files with your zip

 and I see that you are missing config.ini and requirements.txt

**Comment by iharshadec** [comment]
> I am comparing my files with your zip
> 
> and I see that you are missing config.ini and requirements.txt

Oh ! I did download from github website. I think I need to clone recursively your repo?

**Comment by dcelectr** [comment]
You have to clone recursively (I have done it manually in Win10) to get the requirements.
Here is my working zip file
@iharshadec **I updated the zip file** (have another user on Win10 and had issues even after downgrading to python3.8.x After using the updated zip file the plugin icon appeared.
[KiBuzzard.zip](https://github.com/VedantParanjape/KiBuzzard/files/5962892/KiBuzzard.zip)


These files should save the footprint in the c:\Users\Ecloud12\AppData\Temp

**Comment by iharshadec** [comment]
> You have to clone recursively (I have done it manually in Win10) to get the requirements.
> Here is my working zip file
> [KiBuzzard.zip](https://github.com/VedantParanjape/KiBuzzard/files/5916400/KiBuzzard.zip)
> 
> These files should save the footprint in the c:\Users\Ecloud12\AppData\Temp
> .

I really appreciate your help @DCelectronics 

I just have to replace your working KiBuzzard folder to this one -- Correct?

![image](https://user-images.githubusercontent.com/20681096/106705582-3f299180-6614-11eb-9f01-399298e2b0ea.png)

**Comment by dcelectr** [comment]
One directory up (inside directory plugins).
It has all the working deps icons and the kitchen sink.
I am really crossing my fingers that this would work for you.

**Comment by iharshadec** [comment]
> One directory up.
> It has all the working deps icons and the kitchen sink.
> I am really crossing my fingers that this would work for you.

You have done a lot ! I think it's getting late there for you. 
I think there is something else that is messing up and Icon is not coming up next to InteractiveBOM icon I have. :-(

I will try to dig bit more and see what's the thing I am doing wrong.

**Comment by dcelectr** [comment]
Would you please type ```python3 --version``` instead of ```python --version``` in your terminal.
I am suspecting the python3 may not be defined. I may be wrong.

**Comment by iharshadec** [comment]
> Would you please type `python3 --version` instead of `python --version` in your terminal.
> I am suspecting the python3 may not be defined. I may be wrong.

Crap ! I see python3 is not recognized as command on my windows machine. Let me figure out that first and see how can I get python3 as command.

**Comment by dcelectr** [comment]
For the time being, change the python3 to python inside this file 

https://github.com/DCelectronics/KiBuzzard/blob/main/KiBuzzard/__init__.py

This is a workaround, but there are tutorials how to set python3 in windows. 
https://feaforall.com/how-to-install-python-3-on-windows-and-set-the-path/

**Comment by iharshadec** [comment]
> For the time being, change the python3 to python inside this file
> 
> https://github.com/DCelectronics/KiBuzzard/blob/main/KiBuzzard/__init__.py
> 
> This is a workaround, but there are tutorials how to set python3 in windows.
> https://feaforall.com/how-to-install-python-3-on-windows-and-set-the-path/

Now this looks like something else as now I got python3 as a command.
![image](https://user-images.githubusercontent.com/20681096/106725104-ff23d800-662e-11eb-8fa6-c04c4862f9a5.png)

I also copied config.ini file and requirement.txt as well.

Also requirements are installed
![image](https://user-images.githubusercontent.com/20681096/106725257-2f6b7680-662f-11eb-8e3d-4c177b6c552a.png)

Here is my full plugin folder just in case I am putting the folder wrong way.

[plugins.zip](https://github.com/VedantParanjape/KiBuzzard/files/5917294/plugins.zip)

**Comment by dcelectr** [comment]
OK, check if this outputs anything in you CMD terminal.
```python3 C:\Users\Ecloud12\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\deps\buzzard\buzzard.py "test" -o ki-5.1.x -stdout```

I looked at your files and they are OK. I noticed that you had an .git folder inside \plugins\KiBuzzard\ folder which I didn't have in my Win10 setup.

Do you have python2 installed and configured as python when you call it in your CMD terminal?

**Comment by iharshadec** [comment]
> OK, check if this outputs anything in you CMD terminal.
> `python3 C:\Users\Ecloud12\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\deps\buzzard\buzzard.py "test" -o ki-5.1.x -stdout`
> 
> I looked at your files and they are OK. I noticed that you had an .git folder inside \plugins\KiBuzzard\ folder which I didn't have in my Win10 setup.
> 
> Do you have python2 installed and configured as python when you call it in your CMD terminal?

This is what I get using that command.
![image](https://user-images.githubusercontent.com/20681096/106845344-c1778b80-66d0-11eb-9ade-95025a8a9420.png)

Looks like bezier installtion related problem although requirement shows all things are fullfilled. I may need to downgrade my python to your one of 3.8.x

**Comment by dcelectr** [comment]
@iharshadec 
**I updated zip file above** https://github.com/VedantParanjape/KiBuzzard/issues/7#issuecomment-772255504
You should have been getting the polygon points in the terminal, starting like this:
```(module "buzzardLabel" (layer "F.Cu") (tedit "6017799")```
``` (attr virtual)```
``` (fp_poly (pts (xy 1.12 0.02) blah blah...```

>I may need to downgrade my python to your one of 3.8.x

That is the version I have installed in Win10.

**Comment by iharshadec** [comment]
> @iharshadec
> **I updated zip file above** [#7 (comment)](https://github.com/VedantParanjape/KiBuzzard/issues/7#issuecomment-772255504)
> You should have been getting the polygon points in the terminal, starting like this:
> `(module "buzzardLabel" (layer "F.Cu") (tedit "6017799")`
> ` (attr virtual)`
> ` (fp_poly (pts (xy 1.12 0.02) blah blah...`
> 
> > I may need to downgrade my python to your one of 3.8.x
> 
> That is the version I have installed in Win10.

Ok, I updated .zip file and run this command. here is output that I got.

Result:-

> python3 C:\Users\Ecloud12\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\deps\buzzard\buzzard.py "test" -o ki-5.1.x -stdout
> Traceback (most recent call last):
>   File "C:\Users\Ecloud12\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\deps\buzzard\buzzard.py", line 7, in <module>
>     import bezier #pip install bezier
>   File "C:\Users\Ecloud12\AppData\Roaming\Python\Python39\site-packages\bezier\__init__.py", line 29, in <module>
>     from bezier import __config__
>   File "C:\Users\Ecloud12\AppData\Roaming\Python\Python39\site-packages\bezier\__config__.py", line 139, in <module>
>     modify_path()
>   File "C:\Users\Ecloud12\AppData\Roaming\Python\Python39\site-packages\bezier\__config__.py", line 109, in modify_path
>     extra_dll_dir = _get_extra_dll_dir(bezier_files)
>   File "C:\Users\Ecloud12\AppData\Roaming\Python\Python39\site-packages\bezier\__config__.py", line 84, in _get_extra_dll_dir
>     raise ImportError("No DLL directory found", bezier_files)
> ImportError: ('No DLL directory found', [PackagePath('LICENSE'), PackagePath('MANIFEST.in'), PackagePath('README.rst'), PackagePath('setup.cfg'), PackagePath('setup.py'), PackagePath('src/python/bezier/__config__.py'), PackagePath('src/python/bezier/__init__.py'), PackagePath('src/python/bezier/_base.py'), PackagePath('src/python/bezier/_clipping.py'), PackagePath('src/python/bezier/_curve.pxd'), PackagePath('src/python/bezier/_curve_helpers.py'), PackagePath('src/python/bezier/_curve_intersection.pxd'), PackagePath('src/python/bezier/_geometric_intersection.py'), PackagePath('src/python/bezier/_helpers.pxd'), PackagePath('src/python/bezier/_helpers.py'), PackagePath('src/python/bezier/_intersection_helpers.py'), PackagePath('src/python/bezier/_legacy.py'), PackagePath('src/python/bezier/_plot_helpers.py'), PackagePath('src/python/bezier/_speedup.c'), PackagePath('src/python/bezier/_status.pxd'), PackagePath('src/python/bezier/_symbolic.py'), PackagePath('src/python/bezier/_triangle.pxd'), PackagePath('src/python/bezier/_triangle_helpers.py'), PackagePath('src/python/bezier/_triangle_intersection.pxd'), PackagePath('src/python/bezier/_triangle_intersection.py'), PackagePath('src/python/bezier/curve.py'), PackagePath('src/python/bezier/curved_polygon.py'), PackagePath('src/python/bezier/triangle.py'), PackagePath('src/python/bezier.egg-info/PKG-INFO'), PackagePath('src/python/bezier.egg-info/SOURCES.txt'), PackagePath('src/python/bezier.egg-info/dependency_links.txt'), PackagePath('src/python/bezier.egg-info/requires.txt'), PackagePath('src/python/bezier.egg-info/top_level.txt'), PackagePath('src/python/bezier.egg-info/zip-safe'), PackagePath('src/python/bezier/hazmat/__init__.py'), PackagePath('src/python/bezier/hazmat/algebraic_intersection.py'), PackagePath('src/python/bezier/hazmat/curve_helpers.py'), PackagePath('src/python/bezier/hazmat/geometric_intersection.py'), PackagePath('src/python/bezier/hazmat/helpers.py'), PackagePath('src/python/bezier/hazmat/intersection_helpers.py'), PackagePath('src/python/bezier/hazmat/triangle_helpers.py'), PackagePath('src/python/bezier/hazmat/triangle_intersection.py')]):
> python3 C:\Users\Ecloud12\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\deps\buzzard\buzzard.py "test" -o ki-5.1.x -stdout
> Traceback (most recent call last):
>   File "C:\Users\Ecloud12\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\deps\buzzard\buzzard.py", line 7, in <module>
>     import bezier #pip install bezier
>   File "C:\Users\Ecloud12\AppData\Roaming\Python\Python39\site-packages\bezier\__init__.py", line 29, in <module>
>     from bezier import __config__
>   File "C:\Users\Ecloud12\AppData\Roaming\Python\Python39\site-packages\bezier\__config__.py", line 139, in <module>
>     modify_path()
>   File "C:\Users\Ecloud12\AppData\Roaming\Python\Python39\site-packages\bezier\__config__.py", line 109, in modify_path
>     extra_dll_dir = _get_extra_dll_dir(bezier_files)
>   File "C:\Users\Ecloud12\AppData\Roaming\Python\Python39\site-packages\bezier\__config__.py", line 84, in _get_extra_dll_dir
>     raise ImportError("No DLL directory found", bezier_files)
> ImportError: ('No DLL directory found', [PackagePath('LICENSE'), PackagePath('MANIFEST.in'), PackagePath('README.rst'), PackagePath('setup.cfg'), PackagePath('setup.py'), PackagePath('src/python/bezier/__config__.py'), PackagePath('src/python/bezier/__init__.py'), PackagePath('src/python/bezier/_base.py'), PackagePath('src/python/bezier/_clipping.py'), PackagePath('src/python/bezier/_curve.pxd'), PackagePath('src/python/bezier/_curve_helpers.py'), PackagePath('src/python/bezier/_curve_intersection.pxd'), PackagePath('src/python/bezier/_geometric_intersection.py'), PackagePath('src/python/bezier/_helpers.pxd'), PackagePath('src/python/bezier/_helpers.py'), PackagePath('src/python/bezier/_intersection_helpers.py'), PackagePath('src/python/bezier/_legacy.py'), PackagePath('src/python/bezier/_plot_helpers.py'), PackagePath('src/python/bezier/_speedup.c'), PackagePath('src/python/bezier/_status.pxd'), PackagePath('src/python/bezier/_symbolic.py'), PackagePath('src/python/bezier/_triangle.pxd'), PackagePath('src/python/bezier/_triangle_helpers.py'), PackagePath('src/python/bezier/_triangle_intersection.pxd'), PackagePath('src/python/bezier/_triangle_intersection.py'), PackagePath('src/python/bezier/curve.py'), PackagePath('src/python/bezier/curved_polygon.py'), PackagePath('src/python/bezier/triangle.py'), PackagePath('src/python/bezier.egg-info/PKG-INFO'), PackagePath('src/python/bezier.egg-info/SOURCES.txt'), PackagePath('src/python/bezier.egg-info/dependency_links.txt'), PackagePath('src/python/bezier.egg-info/requires.txt'), PackagePath('src/python/bezier.egg-info/top_level.txt'), PackagePath('src/python/bezier.egg-info/zip-safe'), PackagePath('src/python/bezier/hazmat/__init__.py'), PackagePath('src/python/bezier/hazmat/algebraic_intersection.py'), PackagePath('src/python/bezier/hazmat/curve_helpers.py'), PackagePath('src/python/bezier/hazmat/geometric_intersection.py'), PackagePath('src/python/bezier/hazmat/helpers.py'), PackagePath('src/python/bezier/hazmat/intersection_helpers.py'), PackagePath('src/python/bezier/hazmat/triangle_helpers.py'), PackagePath('src/python/bezier/hazmat/triangle_intersection.py')])
>

**Comment by iharshadec** [comment]
Conclusion:
Python 3.9.1 Looks like not working with bezier.
I installed Python 3.8.3 and setup that as python3 for windows. And I used updated .zip from @DCelectronics 
This One and GUI is working on Windows 10 - Kicad 5.1.9 now.
[KiBuzzard.zip](https://github.com/VedantParanjape/KiBuzzard/files/5969937/KiBuzzard.zip)
