### ISSUE TITLE
Can't install KiBuzzard on MacOS

### ISSUE THREAD

**Issue by cyprienh** [VedantParanjape/KiBuzzard#9]
Hello,
I tried installing the plugin on Mac and it never worked. I installed many different versions of KiCad and never got the plugin working.
I couldn't install Bezier 2020.5.19 because I got an error every-time:
`The BEZIER_INSTALL_PREFIX environment variable must be set.`
However I successfully installed version 2020.1.14.
I don't know if that's the source of the problem and I don't know how to fix it so if you could help that would be amazing !
Thanks by advance,
Cyprien

**Comment by dcelectr** [comment]
I do not have macOS to help you on this.
Please read issues https://github.com/VedantParanjape/KiBuzzard/issues/2 and https://github.com/VedantParanjape/KiBuzzard/issues/3#issuecomment-770572193

**Comment by VedantParanjape** [comment]
This is not in active development and changes have been merged into upstream, go to upstream repo. Closing the issue.
